apiVersion: apps/v1
kind: Deployment
metadata:
  name: trucld1-capstone
  labels:
    app: trucld1-capstone
  namespace: default
spec:
  progressDeadlineSeconds: 3600
  replicas: 3
  selector:
    matchLabels:
      app: trucld1-capstone
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: trucld1-capstone
    spec:
      containers:
        - image: truclemsoft/clouddevops-capstone:latest
          imagePullPolicy: Always
          name: clouddevops-capstone
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "500Mi"
              cpu: "500m"
            limits:
              memory: "500Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: trucld1-capstone
  labels:
    app: trucld1-capstone
spec:
  type: LoadBalancer
  selector:
    app: trucld1-capstone
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP